Avoid closing inFile twice in CheckImakefileC if LogFatal returns
Imake's LogFatal() checks if it's being re-entered and if so, returns,
so we can't mark it NORETURN, leading to static analyzers believing it
can return even in call paths it shouldn't.

Resolves warning from Parfait 1.0.1:
Error: File Invalid
   File not Initialized: The value inFile is not initialized as a file.
        at line 748 of imake.c in function 'CheckImakefileC'.
          inFile initialized at line 738 with fopen(masterc, "r").
          inFile destroyed at line 745 with fclose(inFile).

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>